/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package BadDriving;

public class App{

    public static void main(String[] args) throws InterruptedException {

               Car r = new Car();
               r.getDB();

       // Steering hotRod = new Steering();

    }

}

